<a href="https://colab.research.google.com/github/mmilannaik/bostonhousepricing/blob/main/W15S1_SQL_Join_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Install pandasql
!pip install pandasql --quiet

# 2. Load libraries and your CSV into a pandas DataFrame
import pandas as pd
from pandasql import sqldf

# 3. Create a helper to run SQL against any DataFrame in your notebook
pysqldf = lambda query: sqldf(query, globals())

  Preparing metadata (setup.py) ... done
  Building wheel for pandasql (setup.py) ... done

## Freedom Ranking for Different Countries

You can get the dataset from [here](https://drive.google.com/drive/folders/1wr0J571rlfexEJ4-de6_tz1QvU-cJ0df?usp=share_link).

Some feature details of the dataset:

| Feature | Description |
| :--: | :-- |
| A | Electoral Process |
| B | Political Pluralism and Participation |
| C | Functioning of Government |
| D | Freedom of Expression and Belief |
| E | Associational and Organizational Rights |
| F | Rule of Law |
| G | Personal Autonomy and Individual Rights |
| CL | Civil Liberties Scores |
| Status | F=Free, PF=Partly Free, NF=Not Free |


###`Q-1` Find out top 10 countries' which have maximum A and D values.


###`Q-2` Find out highest CL value for 2020 for every region. Also sort the result in descending order. Also display the CL values in descending order.

In [7]:
# 5. Load it into pandas
import pandas as pd
df1 = pd.read_csv('/content/T34_country_ab.csv',sep=';')

df2 = pd.read_csv('/content/T34_country_cd.csv',sep=';')

df3 = pd.read_csv('/content/T34_country_cl.csv',sep=';')

df4 = pd.read_csv('/content/T34_country_efg.csv',sep=';')   # replace with the actual CSV name

In [6]:
df1.head(2)

       Country  Edition   Region  A  B
0     Abkhazia     2022  Eurasia  5  8
1  Afghanistan     2022     Asia  0  0

In [9]:
df2.head(2)

       Country  Edition   Region  C  D
0     Abkhazia     2022  Eurasia  4  8
1  Afghanistan     2022     Asia  1  4

In [16]:
df3.head(2)

       Country  Edition  CL Status
0     Abkhazia     2022  23     PF
1  Afghanistan     2022   9     NF

In [17]:
df2['Edition'].unique()

array([2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013])

In [12]:
df1.columns

Index(['Country', 'Edition', 'Region', 'A', 'B'], dtype='object')

In [22]:
len(df3['Country'].unique())

211

# Q1

In [15]:
pysqldf('''

SELECT  df1.COUNTRY,df1.A,df2.D FROM df1
INNER JOIN df2 ON
df1.Country = df2.Country AND df1.Edition = df2.Edition
ORDER BY A DESC, D DESC
LIMIT 10
''')

      Country   A   D
0    Barbados  12  16
1      Belize  12  16
2  Cabo Verde  12  16
3       Chile  12  16
4  Costa Rica  12  16
5     Denmark  12  16
6     Estonia  12  16
7     Finland  12  16
8     Ireland  12  16
9    Kiribati  12  16

# Q2 : Find out highest CL value for 2020 for every region. Also sort the result in descending order. Also display the CL values in descending order.

In [21]:
pysqldf('''

SELECT Country,MAX(CL)  FROM df3
WHERE Edition = 2020
GROUP BY Country
ORDER BY MAX(CL) DESC
''')

          Country  MAX(CL)
0          Sweden       60
1          Norway       60
2      Luxembourg       60
3         Finland       60
4     Netherlands       59
..            ...      ...
205         Tibet        3
206         Syria        3
207   North Korea        3
208  Turkmenistan        2
209       Eritrea        1

[210 rows x 2 columns]

## Dataset
Data Link-> https://drive.google.com/drive/folders/1bGgNTDy5L_IodNcGHdB_SNCkUI5MUjmY?usp=share_link
Four Tables:
* Customer
* Employee
* Sales
* Products

###`Q-3` Find top-5 most sold products.

### `Q-4:` Find sales man who sold most no of products.

### `Q-5:` Sales man name who has most no of unique customer.

###`Q-6:` Sales man who has generated most revenue. Show top 5.

###`Q-7:` List all customers who have made more than 10 purchases.

### `Q-8` : List all salespeople who have made sales to more than 5 customers.

### `Q-9:` List all pairs of customers who have made purchases with the same salesperson.

In [23]:
cust = pd.read_csv('/content/T34_Customers.csv')
cust.head(2)

   CustomerID FirstName MiddleInitial   LastName
0           1     Aaron           NaN  Alexander
1           2     Aaron           NaN     Bryant

In [24]:
emp = pd.read_csv('/content/T34_Employees.csv')
emp.head(2)

   EmployeeID FirstName MiddleInitial        LastName
0           1   Abraham             e          Bennet
1           2  Reginald             l  Blotchet-Halls

In [25]:
prod = pd.read_csv('/content/T34_Products.csv')
prod.head(2)

   ProductID             Name  Price
0          1  Adjustable Race    1.6
1          2     Bearing Ball    0.8