<a href="https://colab.research.google.com/github/mmilannaik/bostonhousepricing/blob/main/W1_SQL_Window_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Install pandasql
!pip install pandasql --quiet

# 2. Load libraries and your CSV into a pandas DataFrame
import pandas as pd
from pandasql import sqldf

# 3. Create a helper to run SQL against any DataFrame in your notebook
pysqldf = lambda query: sqldf(query, globals())

  Preparing metadata (setup.py) ... done
  Building wheel for pandasql (setup.py) ... done

In [2]:
ipl = pd.read_csv('/content/W16S2_IPL_Ball_by_Ball_2008_2022.csv')
ipl.head(2)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals

In [4]:
ipl.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

# Q1 : Find IPL Batter based on team ans runs scored by them

In [8]:
pysqldf('''
SELECT * FROM(
SELECT BattingTeam,batter,SUM(batsman_run) AS 'total_runs',
DENSE_RANK() OVER(PARTITION BY BattingTeam ORDER BY SUM(batsman_run) DESC) AS 'rank'
FROM ipl
GROUP BY BattingTeam,batter) t
WHERE t.rank <6
ORDER BY t.BattingTeam,t.rank
''')

            BattingTeam         batter  total_runs  rank
0   Chennai Super Kings       SK Raina        4695     1
1   Chennai Super Kings       MS Dhoni        4404     2
2   Chennai Super Kings   F du Plessis        2721     3
3   Chennai Super Kings      AT Rayudu        1774     4
4   Chennai Super Kings     MEK Hussey        1768     5
..                  ...            ...         ...   ...
85  Sunrisers Hyderabad      DA Warner        4016     1
86  Sunrisers Hyderabad       S Dhawan        2518     2
87  Sunrisers Hyderabad  KS Williamson        2105     3
88  Sunrisers Hyderabad      MK Pandey        1346     4
89  Sunrisers Hyderabad    JM Bairstow        1038     5

[90 rows x 4 columns]

# Q2 : Find Runs scored by Virat Kohli in his 50th,100th ,200th Match

In [9]:
pysqldf('''
SELECT ROW_NUMBER() OVER(ORDER BY ID) AS 'match_no',
SUM(batsman_run) AS 'match_run'
FROM ipl
WHERE batter = 'V Kohli'
GROUP BY match_no


''')

PandaSQLException: (sqlite3.OperationalError) misuse of aliased window function match_no
[SQL:
SELECT ROW_NUMBER() OVER(ORDER BY ID) AS 'match_no',
SUM(batsman_run) AS 'match_run'
FROM ipl
WHERE batter = 'V Kohli'
GROUP BY match_no


]
(Background on this error at: https://sqlalche.me/e/20/e3q8)